function ScanText(text) {
    let mText = MarkText(text);
    let newText = mText.text;
    let isFlagged = mText.isFlagged;
    let wText;
    if(newText === text) {
        let splitText = text.split(" "[0]);
        for(let w = 0; w < splitText.length; w++) {
            wText = MarkWord(splitText[w]);
            splitText[w] = wText.text;
            if(wText.isFlagged === true) {
                isFlagged = wText.isFlagged;
            }
        }
        newText = splitText.join(" ");
    }
    return { text: newText, rawText: text, isFlagged: isFlagged };
}
function MarkText(text) {
    let temp = text.toLowerCase();
    for(let m = 0; m < multiWordList.length; m++) {
        if(multiWordList[m].length <= temp.length &&
            temp.includes(multiWordList[m])) {
                return { text: `<span style='background-color: yellow;'>${text}</span>`, isFlagged: true };
            }
    }
    return { text: text, isFlagged: false };
}
function MarkWord(word) {
    let temp = word.toLowerCase();
    for(r = 0; r < singleWordList.length; r++) {
        if(temp.length <= singleWordList.length && 
            temp.toLowerCase().includes(singleWordList[r])) {
            return { text: `<span style='background-color: yellow;'>${word}</span>`, isFlagged: true };
        }
    }
    return { text: word, isFlagged: false };
}
/******************************************************************************/
/******************************************************************************/
// WARNING: horrible words and phrases ahead, listed for flagging purposes...
/******************************************************************************/
/******************************************************************************/
var multiWordList = [
    'ball sack',
    'deep throat',
    'doggie style',
    'doggy style',
    'donkey punch',
    'gang bang',
    'gender bender',
    'hand job',
    'hard on', 
    'jack off',
    'jungle bunny',
    'nut sack',
    'phone sex',
    'porch monkey',
    's hit',
    'shaved beaver',
    'shaved pussy',
    'style doggy',
    'tea bagging',
    'white power'
];
var singleWordList = [
    'a$$',
    'a_s_s',
    'ahole',
    'anal',
    'anilingus',
    'areola',
    'areole',
    'aryan',
    'ass',
    'b!tch',
    'b1tch',
    'balls',
    'ballsack',
    'bastard',
    'beaner',
    'bi+ch',
    'bitch',
    'blowjob',
    'boned',
    'boner',
    'bulldyke',
    'c.0.c.k',
    'c.o.c.k.',
    'c.u.n.t',
    'c0ck',
    'c-0-c-k',
    'c0cksucker',
    'carpetmuncher',
    'child-fucker',
    'ching-chong',
    'chink',
    'circlejerk',
    'cl1t',
    'clit',
    'cock',
    'c-o-c-k',
    'coital',
    'cokmuncher',
    'coksucka',
    'coochie',
    'coochy',
    'coon',
    'corksucker',
    'creampie',
    'cripple',
    'cum',
    'cunilingus',
    'cunillingus',
    'cunnie',
    'cunnilingus',
    'cunny',
    'cunt',
    'd1ck',
    'd1ld0',
    'd1ldo',
    'dago',
    'dammit',
    'damn',
    'darkie',
    'deepthroat',
    'dick',
    'dildo',
    'doggiestyle',
    'doggie-style',
    'doggystyle',
    'doggy-style',
    'dominatrix',
    'dong',
    'donkeypunch',
    'douche',
    'dyke',
    'ejaculate',
    'erotic',
    'f u c k',
    'f.u.c.k',
    'f_u_c_k',
    'fag',
    'fellate',
    'fellatio',
    'fingerbang',
    'fingerfuck',
    'fistfuck',
    'fisting',
    'fleshflute',
    'foreskin',
    'fuck',
    'f-u-c-k',
    'fudgepacker',
    'fudge-packer',
    'fuk',
    'fux',
    'fvck',
    'fxck',
    'gay',
    'genital',
    'goddam',
    'goddammit',
    'gook',
    'gspot',
    'g-spot',
    'guido',
    'h0m0',
    'h0mo',
    'handjob',
    'hardcoresex',
    'heeb',
    'heshe',
    'he-she',
    'hitler',
    'hobag',
    'hoe',
    'hoer',
    'hom0',
    'homo',
    'honkey',
    'hooker',
    'horniest',
    'horny',
    'hotsex',
    'iap',
    'injun',
    'jackoff',
    'jack-off',
    'jap',
    'jigaboo',
    'jiggaboo',
    'jiggerboo',
    'jism',
    'jiz',
    'jizz',
    'junglebunny',
    'kike',
    'klan',
    'kraut',
    'kunilingus',
    'kunt',
    'kyke',
    'lesbo',
    'massa',
    'masturbate',
    'masturbating',
    'masturbation',
    'mick',
    'microphallus',
    'milf',
    'mothafuck',
    'motherfuck',
    'n1gga',
    'n1gger',
    'negro',
    'nigaboo',
    'nigg3r',
    'nigg4h',
    'nigga',
    'nigger',
    'niggle',
    'niglet',
    'nig-nog',
    'nutsack',
    'orgasm',
    'orgies',
    'orgy',
    'p0rn',
    'pedo',
    'penis',
    'piss',
    'polack',
    'pollack',
    'porchmonkey',
    'prick',
    'pube',
    'queer',
    'quim',
    'raghead',
    'rape',
    'raping',
    'rapist',
    'retard',
    'sambo',
    'sh!+',
    'sh!t',
    'sh1t',
    'shemale',
    'shit',
    's-h-i-t',
    'slanteye',
    'slut',
    'spic',
    'squaw',		
    'teabag',
    'testicle',
    'tits',
    'towelhead',
    'tranny',
    'tw4t',
    'twat',
    'wetback',
    'wh0re',
    'whore'
];